import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Routes, Route, Link, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import api from './api';
import { TelegramProvider } from './components/TelegramProvider';
import { useAuthStore } from './store/authStore';
import './index.css';

type Product = { id: number; category_id: number; name: Record<string, string>; description?: Record<string, string>; price_minor: number; currency: string; available: boolean };
type Category = { id: number; name: Record<string, string>; products: Product[] };
type CartLine = { product: Product; quantity: number };
const label = (value: Record<string, string> | undefined, language: string) => value?.[language] || value?.en || Object.values(value || {})[0] || '';
const money = (minor: number, currency: string) => `${(minor / 100).toFixed(2)} ${currency}`;

function LanguageSwitch() { const { i18n } = useTranslation(); return <select aria-label="Language" value={i18n.language} onChange={(e) => i18n.changeLanguage(e.target.value)}><option value="en">English</option><option value="zh-CN">中文</option><option value="km">ខ្មែរ</option></select>; }

function CustomerPage() {
  const { t, i18n } = useTranslation(); const [categories, setCategories] = useState<Category[]>([]); const [cart, setCart] = useState<CartLine[]>([]); const [room, setRoom] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/api/v1/menu').then((r) => setCategories(r.data)).catch(() => setError(t('error.network'))).finally(() => setLoading(false)); }, [t]);
  const total = useMemo(() => cart.reduce((sum, line) => sum + line.product.price_minor * line.quantity, 0), [cart]);
  const add = (product: Product) => setCart((current) => { const found = current.find((line) => line.product.id === product.id); return found ? current.map((line) => line.product.id === product.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { product, quantity: 1 }]; });
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!room.trim()) { setStatus(t('checkout.roomRequired')); return; } try { setStatus(t('checkout.submitting')); const response = await api.post('/api/v1/orders', { room_number: room.trim(), items: cart.map((line) => ({ product_id: line.product.id, quantity: line.quantity })) }, { headers: { 'Idempotency-Key': crypto.randomUUID() } }); setStatus(`${t('payment.title')}: ${response.data.public_code} · ${money(response.data.total_minor, response.data.currency)}`); setCart([]); } catch { setStatus(t('checkout.failed')); } };
  return <main className="customer-shell"><header className="topbar"><div><span className="eyebrow">TEA CAFE</span><h1>{t('menu.title')}</h1></div><LanguageSwitch /></header><section className="hero"><p className="eyebrow">{t('menu.popular')}</p><h2>{t('brand')}</h2><p>{t('checkout.roomOnly')}</p></section>{loading && <p className="state">{t('common.loading')}</p>}{error && <p className="error">{error}</p>}<section className="menu-grid">{categories.map((category) => <div className="category" key={category.id}><h2>{label(category.name, i18n.language)}</h2><div className="product-grid">{category.products.map((product) => <article className="product-card" key={product.id}><div className="product-art">{label(product.name, i18n.language).slice(0, 1)}</div><div className="product-copy"><h3>{label(product.name, i18n.language)}</h3><p>{label(product.description, i18n.language)}</p><div className="product-foot"><strong>{money(product.price_minor, product.currency)}</strong><button onClick={() => add(product)}>{t('menu.addToCart')}</button></div></div></article>)}</div></div>)}</section><section className="checkout-card"><div><span className="eyebrow">{t('cart.title')}</span><h2>{cart.length ? `${cart.length} ${t('common.quantity')}` : t('cart.empty')}</h2></div>{cart.length > 0 && <form onSubmit={submit}><label htmlFor="room">{t('checkout.roomNumber')}</label><input id="room" value={room} onChange={(e) => setRoom(e.target.value)} inputMode="numeric" placeholder="508" /><div className="total-row"><span>{t('common.total')}</span><strong>{money(total, cart[0].product.currency)}</strong></div><button className="primary" type="submit">{t('checkout.placeOrder')}</button></form>}{status && <p className="status" role="status">{status}</p>}</section></main>;
}

function AdminLogin() { const { t } = useTranslation(); const navigate = useNavigate(); const { setAdminAuth } = useAuthStore(); const [login, setLogin] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = async (e: FormEvent) => { e.preventDefault(); try { const r = await api.post('/api/v1/auth/admin/login', { login_name: login, password }); setAdminAuth(String(r.data.staff_id), r.data.role); navigate('/admin'); } catch { setError(t('auth.loginFailed')); } }; return <main className="auth-shell"><div className="auth-card"><div className="brand-mark">T</div><span className="eyebrow">TEA CAFE · STAFF CONSOLE</span><h1>{t('auth.loginTitle')}</h1><p>{t('auth.loginDescription')}</p><form onSubmit={submit}><label htmlFor="login">{t('auth.loginId')}</label><input id="login" value={login} onChange={(e) => setLogin(e.target.value)} autoComplete="username" required /><label htmlFor="password">{t('auth.password')}</label><input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" required />{error && <p className="error">{error}</p>}<button className="primary" type="submit">{t('auth.login')}</button></form><LanguageSwitch /></div></main>; }

function AdminPage() { const { t } = useTranslation(); const { isAdminAuthenticated, logoutAdmin } = useAuthStore(); const [orders, setOrders] = useState<any[]>([]); const [error, setError] = useState(''); useEffect(() => { if (!isAdminAuthenticated) return; api.get('/api/v1/admin/orders').then((r) => setOrders(r.data)).catch(() => setError(t('error.network'))); }, [isAdminAuthenticated, t]); if (!isAdminAuthenticated) return <AdminLogin />; return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">FOOD.WORKLINE.INK/ADMIN</span><h1>{t('nav.overview')}</h1></div><div className="header-actions"><LanguageSwitch /><button onClick={logoutAdmin}>{t('auth.logout')}</button></div></header><section className="metric-row"><div className="metric"><span>{t('admin.ordersToday')}</span><strong>{orders.length}</strong></div><div className="metric warning"><span>{t('admin.needsReview')}</span><strong>{orders.filter((o) => o.payment_status === 'PROOF_SUBMITTED').length}</strong></div><div className="metric"><span>{t('admin.confirmedPaid')}</span><strong>{orders.filter((o) => o.payment_status === 'PAID_CONFIRMED').length}</strong></div></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">{t('admin.orders')}</span><h2>{t('nav.orders')}</h2></div><Link to="/">{t('nav.menu')}</Link></div>{error && <p className="error">{error}</p>}{orders.length === 0 ? <p className="state">{t('common.loading')}</p> : <div className="order-list">{orders.map((order) => <div className="order-row" key={order.id}><strong>{order.public_code}</strong><span>{t('checkout.roomNumber')} {order.room_number}</span><span>{order.payment_status}</span><b>{money(order.total_minor, order.currency)}</b></div>)}</div>}</section></main>; }

export default function App() { return <TelegramProvider><Routes><Route path="/" element={<CustomerPage />} /><Route path="/admin/login" element={<AdminLogin />} /><Route path="/admin" element={<AdminPage />} /></Routes></TelegramProvider>; }
